config/routes.rb
Rails.application.routes.draw do
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dictionary_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :place)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :place)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:search]
      @search_term = params[:search]
  end

  def about
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Simple Design ROR App', root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
      <%= link_to "Screen 1", home_about_path, class:"nav-link" %> 
      </li>

      <li class="nav-item">
      <%= link_to "Screen 2", friends_path, class:"nav-link" %>  
      </li>

      <li class="nav-item">
      <%= link_to "Screen 3", new_friend_path, class:"nav-link" %>
      </li>

    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<p>Enter a keyword<p>
<form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
<br>


<div class="jumbotron-fluid">
  <div class="container">
    <h3 class="display-8">Word of the day</h3>
    <p class="lead">Hello: used as a greeting or to begin a phone conversation</p>
  </div>
</div>

def self.search_by (search_term)
  where("Live(word)" linke :search_term"), search_term: %# {search_term.live}"

app/views/home/index.html.erb
<h1>Welcome to Simple Design of ROR App</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Simple Design</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= audio_tag "sample-6s.mp3",id:"sound", class: "audio-to-play", autoplay: true %>
    <%= render 'home/header' %>
    <div class ="container">
    <br/>
       <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/screens/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :place, style: "display: block" %>
    <%= form.text_field :place %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/screens/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= friend.place %>
  </p>

</div>

app/views/screens/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/screens/index.html.erb
<p>Live<p>
<form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

<br>

<div class="jumbotron-fluid">
  <div class="container">
    <h4 class="display-8"></h4>
    <p class="lead">Live</p>
    <p class="lead">to be alive,to have life.</p>
  </div>
</div>
<br>
<div class="jumbotron-fluid">
  <div class="container">
    <h4 class="display-8"></h4>
    <p class="lead">Live</p>
    <p class="lead">to have permanenet residence..</p>
  </div>
</div>
<br>
<div class="jumbotron-fluid">
  <div class="container">
    <h4 class="display-8"></h4>
    <p class="lead">Live</p>
     <p class="lead">to survive; to persevere.</p>
  </div>
</div>
<br>
<div class="jumbotron-fluid">
  <div class="container">
    <h4 class="display-8"></h4>
    <p class="lead">Live</p>
    <p class="lead">to make the most of life.</p>
  </div>
</div>

app/views/screens/new.html.erb
<div class="jumbotron-fluid">
  <div class="container">
    <h4 class="display-8"></h4>
    <b class="lead">Live</b>
    <p class="lead">Pronuunciation: <b> /liv/</b>
<br></br>

    <div class="jumbotron-fluid">
        <div class="container">
          <h4 class="display-8"></h4>
            <b class="lead">verb:</b>
              <p class="lead">To be alive. To have life.</p>
              <p> eg: He's not expected to live for more than a few months. </p>
<br>
    <div class="jumbotron-fluid">
      <div class="container">
        <h4 class="display-8"></h4>
          <b class="lead">Noun:</b>
            <p class="lead">Having life. THat is alive.</p>
            <p> eg:The post office will not ship live animals. </p>
<br>

     <div class="jumbotron-fluid">
      <div class="container">
        <h4 class="display-8"></h4>
          <b class="lead">Noun:</b>
            <p class="lead">Having life. THat is alive.</p>
            <p> eg:The post office will not ship live animals. </p>

<br>

  <div class="jumbotron-fluid">
    <div class="container">
      <h4 class="display-8"></h4>
        <b class="lead">Adverb:</b>
        <p class="lead">Of an event, as it happens: in real time: direct.</p>
        <p> eg: The concert was broadcasr live by radio. </p>

app/views/screens/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
  <%= @friend.first_name %>
  <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %> | <%= @friend.phone %> | <%= @friend.place %>
  <br></br>
  <%= link_to "Edit ", edit_friend_path(@friend), class:"btn btn-secondary" %> 
  <%= link_to "delete ", @friend, method: :delete,data: {confrim: 'are you sure?' }, class:"btn btn-secondary" %> 
  <%= link_to "Back ", friends_path, class:"btn btn-secondary" %>
  
</div>